### ISSUE TITLE
How do i update the point cloud in real time? 

### ISSUE THREAD

**Issue by ayushmankumar7** [ErenBalatkan/DepthVisualizer-Examples#2]
I have multiple RBG images with their corresponding Depth Maps... Now I want to render it as if the point clouds are changing as shown in your main repo's README. How do I do that..

**Comment by ayushmankumar7** [comment]
I figured it out... Hence closing this issue. You made a great tool! Thank you <3

**Comment by ErenBalatkan** [comment]
Your welcome! Ideally I should make this operate async from main thread but I don't have enough time to make a revision.

**Comment by BurhanUlTayyab** [comment]
Same Question here, can you kindly tell me how to do it?
